### ISSUE TITLE
TokenAllocator breaks after  Creating  <Module> Constructor

### ISSUE THREAD

**Issue by JPaja** [Washi1337/AsmResolver#187]
## Describe the bug
After we assign tokens to some new members and add them to module, and after that we 
Create <Module> Construtor. When writing file 2 module constructor and 1 of new members will have conflicting metadata token

## To Reproduce
```csharp
var targetModule = ModuleDefinition.FromFile("HelloWorld.dll");

var retType = targetModule.CorLibTypeFactory.Boolean;
var method = new MethodDefinition("test", MethodAttributes.Public | MethodAttributes.Static , MethodSignature.CreateStatic(retType));
var body = new CilMethodBody(method);
body.Instructions.Add(new CilInstruction(CilOpCodes.Ldc_I4, 0));
body.Instructions.Add(new CilInstruction(CilOpCodes.Ret));
method.CilMethodBody = body;

targetModule.TopLevelTypes.First().Methods.Add(method);

var allocator = targetModule.TokenAllocator;
allocator.AssignNextAvailableToken(method);

targetModule.GetModuleType().GetOrCreateStaticConstructor();

var imageBuilder  = new ManagedPEImageBuilder(MetadataBuilderFlags.PreserveAll);
var result = imageBuilder.CreateImage(targetModule);
if (!result.DiagnosticBag.IsFatal)
{
    var fileBuilder = new ManagedPEFileBuilder();
    var file = fileBuilder.CreateFile(result.ConstructedImage);
    file.Write("output.dll");
}
else
{
    foreach(var exception in result.DiagnosticBag.Exceptions)
        Console.WriteLine(exception);
}
```

## Expected behavior
There should not be conflict between tokens

## Screenshots
```
System.ArgumentException: System.Void <Module>::.cctor() and System.Boolean <Module>::test() (0x06000003) are assigned the same RID 3.
   at AsmResolver.DotNet.Builder.Discovery.MemberDiscoverer.InsertOrAppendIfNew[TMember](TMember member)
   at AsmResolver.DotNet.Builder.Discovery.MemberDiscoverer.CollectNewlyAddedMembers()
   at AsmResolver.DotNet.Builder.Discovery.MemberDiscoverer.DiscoverMembersInModule(ModuleDefinition module, MemberDiscoveryFlags flags)
   at AsmResolver.DotNet.Builder.DotNetDirectoryFactory.DiscoverMemberDefinitionsInModule(ModuleDefinition module)
   at AsmResolver.DotNet.Builder.DotNetDirectoryFactory.CreateDotNetDirectory(ModuleDefinition module, INativeSymbolsProvider symbolsProvider, DiagnosticBag diagnosticBag)
   at AsmResolver.DotNet.Builder.ManagedPEImageBuilder.CreateImage(ModuleDefinition module)
   ```

## Platform
 - OS: Windows 10
 - AsmResolver Version: 4.6

**Comment by Washi1337** [comment]
Potential fix has been pushed to branch [issue/187](/Washi1337/AsmResolver/tree/issue/187). Can you verify that this indeed solves your problem?

**Comment by JPaja** [comment]
It's all good 👍
