### ISSUE TITLE
DefaultMetadataResolver is not thread safe

### ISSUE THREAD

**Issue by SamboyCoding** [Washi1337/AsmResolver#269]
## Describe the bug
Attempting to call TypeReference.Resolve() (or any property which requires a resolved reference, such as IsValueType) from multiple threads concurrently causes an exception:

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at AsmResolver.DotNet.DefaultMetadataResolver.LookupInCache(ITypeDescriptor type)
   at AsmResolver.DotNet.DefaultMetadataResolver.ResolveTypeReference(TypeReference reference)
   at AsmResolver.DotNet.DefaultMetadataResolver.ResolveType(ITypeDescriptor type)
   at AsmResolver.DotNet.TypeReference.Resolve()
   at AsmResolver.DotNet.TypeReference.get_IsValueType()
   at AsmResolver.DotNet.TypeReference.ToTypeSignature()
--snip--
```

## To Reproduce
Create a bunch of type references, then convert them to type signatures, from many threads, e.g. using Parallel.ForEach. 

## Expected behavior
No exception was thrown, as ConcurrentDictionary or a lock was used.

## Screenshots
N/A - stacktrace provided above.

## Platform
 - OS: Windows 11
 - AsmResolver Version: 4.9.0

**Additional context**
As said above, a simple fix to this problem would probably be to switch DefaultMetadataResolver to use a ConcurrentDictionary as its backing cache.

**Comment by Washi1337** [comment]
`ConcurrentDictionary` seems like the way to go. If you want you can send a PR if you have an idea on how to implement it :)
