### ISSUE TITLE
Rewrite Assembly Failure

### ISSUE THREAD

**Issue by ds5678** [Washi1337/AsmResolver#378]
### AsmResolver Version

5.0.0 beta 2

### .NET Version

.NET 6.0

### Operating System

Windows

### Describe the Bug

I found a couple assemblies in Mono Unity games that fail to rewrite after being read.

### How To Reproduce

```cs
AssemblyDefinition assembly = AssemblyDefinition.FromFile(@"path");
MemoryStream memoryStream = new();
assembly.WriteManifest(memoryStream);
```
[mscorlib.zip](https://github.com/Washi1337/AsmResolver/files/9991572/mscorlib.zip)

### Expected Behavior

It should successfully write to the stream.

### Actual Behavior

```
Unhandled exception. System.AggregateException: Construction of the PE image failed with one or more errors. (Attempted to read past the end of the stream.)
 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at AsmResolver.IO.BinaryStreamReader.ReadByte()
   at AsmResolver.DotNet.Signatures.Marshal.LPArrayMarshalDescriptor.FromReader(BinaryStreamReader& reader)
   at AsmResolver.DotNet.Signatures.Marshal.MarshalDescriptor.FromReader(ModuleDefinition parentModule, BinaryStreamReader& reader)
   at AsmResolver.DotNet.Serialized.SerializedModuleDefinition.GetFieldMarshal(MetadataToken ownerToken)
   at AsmResolver.LazyVariable`1.InitializeValue()
   at AsmResolver.DotNet.ParameterDefinition.get_MarshalDescriptor()
   at AsmResolver.DotNet.Builder.DotNetDirectoryBuffer.AddFieldMarshal(MetadataToken ownerToken, IHasFieldMarshal owner)   at AsmResolver.DotNet.Builder.DotNetDirectoryBuffer.FinalizeParametersInMethod(MethodDefinition method, UInt32& paramList, Boolean& paramPtrRequired)
   at AsmResolver.DotNet.Builder.DotNetDirectoryBuffer.FinalizeMethods(Boolean& paramPtrRequired)
   at AsmResolver.DotNet.Builder.DotNetDirectoryBuffer.FinalizeTypes()
   at AsmResolver.DotNet.Builder.DotNetDirectoryFactory.CreateDotNetDirectory(ModuleDefinition module, INativeSymbolsProvider symbolsProvider, DiagnosticBag diagnosticBag)
   at AsmResolver.DotNet.Builder.ManagedPEImageBuilder.CreateImage(ModuleDefinition module)
   --- End of inner exception stack trace ---
   at AsmResolver.DotNet.ModuleDefinition.ToPEImage(IPEImageBuilder imageBuilder)
   at AsmResolver.DotNet.AssemblyDefinition.WriteManifest(Stream stream)
   at Program.Main(String[] args)
```

### Additional Context

This was part of a Unity 2020.2.0f1 build.

**Comment by Washi1337** [comment]
Seems like LPArray marshal descriptors are not required to have an explicit element type.

Potential fix is in #379.
