### ISSUE TITLE
Nested type Sort Error？

### ISSUE THREAD

**Issue by Luoosa** [Washi1337/AsmResolver#545]
### AsmResolver Version

5.5.1

### .NET Version

.NET 4.8 X64

### Operating System

Windows

### Describe the Bug

Error Log：

> Construction finished with 2 errors.
> Nested type oxM=+ohM= (0x02000081) is added before its enclosing class oxM= (0x0
> 2000082).
> Expected Identifier.
> 
> Unhandled Exception: System.ArgumentException: Image does not contain a .NET dir
> ectory.
>    at AsmResolver.PE.DotNet.Builder.ManagedPEFileBuilder.ManagedPEBuilderContext
> ..ctor(IPEImage image)
>    at AsmResolver.PE.DotNet.Builder.ManagedPEFileBuilder.CreateContext(IPEImage
> image)
>    at AsmResolver.PE.Builder.PEFileBuilderBase`1.CreateFile(IPEImage image)
>    at JitDumper.Program.Main(String[] args)

File：
![QQ截图20240324130932](https://github.com/Washi1337/AsmResolver/assets/9017552/2a2da200-f06b-4bb0-8b65-a0a597ba528e)
![QQ截图20240324131110](https://github.com/Washi1337/AsmResolver/assets/9017552/dbd4ec55-3574-4380-9aaa-07111edbfefd)

How can i fix，thanks？

### How To Reproduce

1

### Expected Behavior

1

### Actual Behavior

1

**Comment by Washi1337** [comment]
> How can i fix，thanks？
> 
> ### How To Reproduce
> 
> 1
> 
> ### Expected Behavior
> 
> 1
> 
> ### Actual Behavior
> 
> 1
> 

This is going to be hard to diagnose if I don't have a way to reproduce this problem.

**Comment by Washi1337** [comment]
I still have no way to actually reproduce and/or diagnose your issue. Is it possible to provide example code, binaries, or steps to trigger the error? Otherwise I can't do much.

**Comment by Washi1337** [comment]
Closed for inactivity. Feel free to reopen the issue if you still have this problem.

**Comment by gotmachine** [comment]
Using AsmResolver 6.0 b3, I'm having the exact same issue (`Nested type oxM=+ohM= is added before its enclosing class oxM=`) with same looking implementations for those, but on a different dll obfuscated with the same stuff (AgileDotNet).

Will send the problematic dll over discord in private.

**Comment by Washi1337** [comment]
@gotmachine Potential fix has been pushed in #625.

Keep in mind that this still technically is invalid metadata, and as such, AsmResolver will by default  throw when nested types are defined before their enclosing types (that is, their RID is lower than their enclosing type's RID). The PR should make it safe now to ignore this builder exception. See also [Image Builder Diagnostics](https://docs.washi.dev/asmresolver/guides/dotnet/advanced-pe-image-building.html#image-builder-diagnostics) on how to ignore non-fatal builder exceptions.
